on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/_lint.yml
  test:
    uses: ./.github/workflows/_test.yml
  e2e:
    uses: ./.github/workflows/_e2e.yml
